# Compare 335 links with other NHPs.

```{r}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, eval=FALSE)
```

```{r}
# load packages
library(dplyr)
library(RCy3)
library(biomaRt)
library(twice)
library(TEKRABber)
```

```{r}
# load 335 links
c1_335 <- read.csv("../tables/c1_confirm_correlation.csv")

# load NHP results
load("~/github/primate_network/data/c1c2_NHPs.RData")

# load correlation tables
HmC1 <- read.csv("../tables/hsC1_corr_sig.csv")
HmC1 <- HmC1 %>% 
    filter(pair %in% c1_335$x)

# load NHP result
PtC1 <- c1c2_NHPs$pt_c1 %>% filter(pvalue<0.05)
PpC1 <- c1c2_NHPs$pp_c1 %>% filter(pvalue<0.05)
MmC1 <- c1c2_NHPs$mm_c1 %>% filter(pvalue<0.05)

# then add age information to the table
young_kznf <- kznf_infer %>% filter(age=="young")
young_te <- te_infer$NM

HmC1_age <- HmC1 %>%
    mutate(age=ifelse(geneName %in% young_kznf$external_gene_name |
                           teName %in% young_te, "young", "old"))
```

Analyze different direction and add evolutionary age information:

```{r eval=FALSE}
nhp_c1 <- unique(c(PtC1$pair, PpC1$pair, MmC1$pair))

Hm_diff <- HmC1_age %>%
    filter(!pair %in% nhp_c1)

Hm_Pt_diff <- HmC1_age %>%
    inner_join(PtC1[,c(3,6)], join_by(pair==pair)) %>%
    mutate(sign=ifelse(sign(coef.x) * sign(coef.y) <0, "opposite", "same"))

Hm_Pp_diff <- HmC1_age %>%
    inner_join(PpC1[,c(3,6)], join_by(pair==pair)) %>%
    mutate(sign=ifelse(sign(coef.x) * sign(coef.y) <0, "opposite", "same"))

Hm_Mm_diff <- HmC1_age %>%
    inner_join(MmC1[,c(3,6)], join_by(pair==pair)) %>%
    mutate(sign=ifelse(sign(coef.x) * sign(coef.y) <0, "opposite", "same"))
```

```{r eval=FALSE}
# make human specific 197 link network by excluding overlap in NHPs
c1_hm_diff_node <- data.frame(
    id=c(unique(Hm_diff$geneName), unique(Hm_diff$teName))
)

c1_hm_diff_link <- Hm_diff %>% dplyr::select(c(1,2,3,7))
colnames(c1_hm_diff_link) <- c("source", "target", "coefficient", "age")

createNetworkFromDataFrames(c1_hm_diff_node, c1_hm_diff_link)

# Hm_Pt_diff
c1_HmPt_diff_node <- data.frame(
    id=c(unique(Hm_Pt_diff$geneName), unique(Hm_Pt_diff$teName))
)

c1_HmPt_diff_link <- Hm_Pt_diff %>% dplyr::select(c(1,2,3,8,7,9))
colnames(c1_HmPt_diff_link) <- c("source", "target", "coef_h", "coef_p", "age", "sign")

createNetworkFromDataFrames(c1_HmPt_diff_node, c1_HmPt_diff_link)

# Hm_Pp_diff
c1_HmPp_diff_node <- data.frame(
    id=c(unique(Hm_Pp_diff$geneName), unique(Hm_Pp_diff$teName))
)

c1_HmPp_diff_link <- Hm_Pp_diff %>% dplyr::select(c(1,2,3,8,7,9))
colnames(c1_HmPp_diff_link) <- c("source", "target", "coef_h", "coef_p", "age", "sign")

createNetworkFromDataFrames(c1_HmPp_diff_node, c1_HmPp_diff_link)

# Hm_Mm_diff
c1_HmMm_diff_node <- data.frame(
    id=c(unique(Hm_Mm_diff$geneName), unique(Hm_Mm_diff$teName))
)

c1_HmMm_diff_link <- Hm_Mm_diff %>% dplyr::select(c(1,2,3,8,7,9))
colnames(c1_HmMm_diff_link) <- c("source", "target", "coef_h", "coef_p", "age", "sign")

createNetworkFromDataFrames(c1_HmMm_diff_node, c1_HmMm_diff_link)
```

Filter out TEs in each network

```{r}
# save the gene and TE list
write.csv(Hm_diff, file="../tables/c1_197_Hm_DiffNHP.csv")
write.csv(Hm_Pt_diff, file="../tables/c1_45_HmPt_Diff.csv")
write.csv(Hm_Pp_diff, file="../tables/c1_99_HmPp_Diff.csv")
write.csv(Hm_Mm_diff, file="../tables/c1_30_HmMm_Diff.csv")
```

We run correlation on protein-coding genes

```{r eval=FALSE}
# get ensembl human protein coding gene
ensembl_hm <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
hm_protein <- getBM(attributes = c("ensembl_gene_id", "external_gene_name"),
                    filters = "biotype", values = "protein_coding",
                    mart=ensembl_hm) #23214
```

Get expression file

```{r}
load("~/github/primate_network/data/primateBrainData.RData")

# genes
df_hm_gene <- hmGene[,c(-1)]
rownames(df_hm_gene) <- hmGene$geneID

# transposable elements
hsTEexp <- hmTE %>% dplyr::select(-c(1,2,3))
rownames(hsTEexp) <- hmTE$name  #908 TEs

# genes convert to tpm
sample_counts <- colSums(df_hm_gene)

scaling_factor <- sample_counts / 1e6

df_hm_gene_tpm <- df_hm_gene
df_hm_gene_tpm <- t(t(df_hm_gene_tpm)/ scaling_factor + 1) * 1e6
df_hm_gene_tpm <- as.data.frame(df_hm_gene_tpm)

# tes convert to tpm
te_count <- colSums(hsTEexp)
te_scale <- te_count / 1e6
hsTE_tpm <- hsTEexp
hsTE_tpm <- t(t(hsTE_tpm)/ te_scale + 1) * 1e6
hsTE_tpm <- as.data.frame(hsTE_tpm)

# and prepare the select dataframe
# filter only protein-coding genes
df_hm_gene_tpm_protein <- 
    df_hm_gene_tpm[rownames(df_hm_gene_tpm)%in%hm_protein$ensembl_gene_id,]
df_hm_gene_tpm_protein <- df_hm_gene_tpm_protein %>%
    mutate(id=rownames(.)) %>%
    left_join(hm_protein, join_by(id==ensembl_gene_id))
df_hm_gene_tpm_protein <- df_hm_gene_tpm_protein[!duplicated(df_hm_gene_tpm_protein$external_gene_name),]

rownames(df_hm_gene_tpm_protein) <- df_hm_gene_tpm_protein$external_gene_name

cluster_meta <- read.csv("../data/cluster_meta.csv")
cluster_id_c1 <- cluster_meta %>% 
    filter(cluster=="cluster1") %>%
    dplyr::select(1)

df_hm_gene_tpm_protein_c1 <- df_hm_gene_tpm_protein %>%
    dplyr::select(cluster_id_c1$Run) # get 19266 protein coding genes, and 40 sample

# next we select (1) protein-coding genes (without KRAB-ZNF) (2) select KRAB-ZNF
df_hm_gene_tpm_protein_c1_gene <- df_hm_gene_tpm_protein_c1 %>%
    filter(!rownames(.) %in% kznf_infer$external_gene_name) #18930

df_hm_tpm_c1_kznf <- df_hm_gene_tpm_protein_c1 %>%
    filter(rownames(.) %in% unique(Hm_diff$geneName)) #46

hsTE_tpm_c1_select <- hsTE_tpm %>% 
    dplyr::select(cluster_id_c1$Run) %>% 
    filter(rownames(.) %in% Hm_diff$teName) #122

hsc1_protein_kznf <- corrOrthologTE(
    df_hm_gene_tpm_protein_c1_gene,
    df_hm_tpm_c1_kznf,
    numCore = 5 
)

hsc1_protein_TE <- corrOrthologTE(
    df_hm_gene_tpm_protein_c1_gene,
    hsTE_tpm_c1_select,
    numCore = 5
)

## filter data
# 1. padj<0.05
c1_protein_kznf_sig <- hsc1_protein_kznf %>% 
    filter(padj<0.01 & abs(coef)>=0.7)
c1_protein_TE_sig <- hsc1_protein_TE %>% 
    filter(padj<0.01 & abs(coef) >=0.7)

#2. get the pair of TE:KRAB-ZNF
df_temp <- data.frame(gene=list(), kznf=character(), TE=character(), stringsAsFactors = F)

for (i in 1:nrow(Hm_diff)){
    kznf <- Hm_diff[i, "geneName"]
    te <- Hm_diff[i, "teName"]
    
    protein_gene_kznf <- 
        c1_protein_kznf_sig[c1_protein_kznf_sig$teName==kznf, ]$geneName
    
    protein_te_kznf <- 
        c1_protein_TE_sig[c1_protein_TE_sig$teName==te, ]$geneName
    
    intersect_gene <- intersect(protein_gene_kznf, protein_te_kznf)
    
    if (!is.null(protein_gene_kznf) & 
        !is.null(protein_te_kznf) & 
        !is.null(intersect_gene)){
    
        df_temp_1 <- data.frame(
            gene = intersect_gene,
            kznf = kznf,
            TE = te
        )
    
        df_temp <- rbind(df_temp, df_temp_1)
    
    }
}

df_temp_process <- df_temp %>%
    left_join(c1_protein_kznf_sig[,c(1,2,3)], 
              by=c("gene"="geneName", "kznf"="teName")) %>%
    left_join(c1_protein_TE_sig[,c(1,2,3)], 
              by=c("gene"="geneName", "TE"="teName")) %>%
    left_join(Hm_diff[,c(1,2,3)], by=c("kznf"="geneName", "TE"="teName"))

colnames(df_temp_process)[c(4,5,6)] <- c("coef.kznf", "coef.TE", "coef.kznf.TE") 

df_temp_process_select <- df_temp_process %>% 
    filter(coef.kznf * coef.TE < 0 & coef.TE * coef.kznf.TE > 0) %>%
    filter(abs(coef.kznf)>=0.85 & abs(coef.TE)>=0.85)
```

# cluster 2

```{r}
# load 335 links
c2_64 <- read.csv("../tables/c2_confirm_correlation.csv")

# load correlation tables
HmC2 <- read.csv("../tables/hsC2_corr_sig.csv")
HmC2 <- HmC2 %>% 
    filter(pair %in% c2_64$x)

# load NHP result
PtC2 <- c1c2_NHPs$pt_c2 %>% filter(pvalue<0.05)
PpC2 <- c1c2_NHPs$pp_c2 %>% filter(pvalue<0.05)
MmC2 <- c1c2_NHPs$mm_c2 %>% filter(pvalue<0.05)

# then add age information to the table
young_kznf <- kznf_infer %>% filter(age=="young")
young_te <- te_infer$NM

HmC2_age <- HmC2 %>%
    mutate(age=ifelse(geneName %in% young_kznf$external_gene_name |
                           teName %in% young_te, "young", "old"))

nhp_c2 <- unique(c(PtC2$pair, PpC2$pair, MmC2$pair))

Hm_diff <- HmC2_age %>%
    filter(!pair %in% nhp_c2)

write.csv(Hm_diff, file="../tables/c2_35_Hm_DiffNHP.csv", row.names=F)
```
