# Check age cut continuous data

```{r}
library(tidyverse)
library(twice)
library(ggplot2)
library(ggpubr)
```

First, we load the expression data:

```{r}
# expression data
HmPtC1 <- readRDS("../data/HmPtC1.rds")
HmPpC1 <- readRDS("../data/HmPpC1.rds")
HmMmC1 <- readRDS("../data/HmMmC1.rds")
```

Then, we preprocess the age data to continuous data,

For KZNFs,

```{r}
# for KRAB-ZNFs, we merge the kznf_infer data with geneTree
gentree <- read.table("~/Downloads/hg38_ver95_age.tsv", sep="\t", header=TRUE)

kznf_infer_branch <- kznf_infer %>%
    inner_join(gentree[,c(1,3)], join_by(ensembl_gene_id==gene))

# remove conflict
kznf_infer_branch_preprocess <- kznf_infer_branch %>%
    filter(!external_gene_name %in% c("ZNF564", "ZNF37A", "ZNF658"))

branch_table <- data.frame(
    branch = c(1,2,3,4,5,6,7,8,9,10,12,13,14),
    taxo = c("Tetrapoda", "Amniota", "Mammalia", "Theria", "Eutheria",
             "Boreoeutheria", "Euarchontoglires", "Simiiformes", "Catarrhini",
             "Hominoidea", "H.sapiens & P.troglodytes", "Homo sapiens", "Homo sapiens")
)

# merge table
kznf_infer_branch_preprocess_taxo <- kznf_infer_branch_preprocess %>%
    select(c(2,6,7)) %>%
    inner_join(branch_table, join_by(branch==branch))
```

Expression of KRAB-ZNFs and visualization

```{r}
hm_kznf <- HmPtC1$DEobject$gene_res %>%
    data.frame() %>%
    mutate(gene = rownames(.)) %>%
    inner_join(kznf_infer_branch_preprocess_taxo, join_by(gene==external_gene_name))

hm_kznf$taxo <- factor(hm_kznf$taxo, levels=branch_table$taxo[1:12])

g_hm_kznf <- ggplot(hm_kznf, aes(x=taxo, y=baseMean)) +
    geom_boxplot(fill = "#C087F8", color="black", outlier.shape = NA) +
    xlab("") +
    ylab("exp") +
    ylim(0, 800) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 70, vjust= 0.6, hjust=0.5)) 
    
```

For TEs,

```{r}
te_annot <- readLines("~/Downloads/Dfam_curatedonly.embl")

# initialize variable
TE_list <- c()
species_list <- c()
clade_list <- c()
NM <- NULL
OC <- NULL
OS <- NULL

# Loop
for (line in te_annot) {
    
    if (grepl("^NM\\s+", line)) {
        NM <- sub("^NM\\s+", "", line)
    }
    
    if (grepl("^OC\\s+", line)) {
        oc_values <- sub("^OC\\s+", "", line)
        oc_values <- strsplit(oc_values, ";")[[1]]
        OC <- trimws(tail(oc_values, n=1))
    }
    
    if (grepl("^OS\\s+", line)) {
        OS <- sub("^OS\\s+", "", line)
    }
    
    if (grepl("^//", line) && !is.null(NM) && !is.null(OC)) {
        TE_list <- c(TE_list, NM)
        clade_list <- c(clade_list, OC)
        species_list <- c(species_list, OS)
        NM <- NULL
        OC <- NULL
        OS <- NULL
    }
    
}

df_te_extract <- data.frame(TE = TE_list, 
                            species = species_list, 
                            clade = clade_list,
                            stringsAsFactors = FALSE)

clade <- c("Euteleostomi", "Tetrapoda", "Amniota", "Mammalia", "Theria <mammals>",
           "Eutheria", "Afrotheria", "Boreoeutheria", "Artiodactyla",
           "Euarchontoglires","Glires", "Rodentia", "Primates", "Haplorrhini",
           "Simiiformes", "Catarrhini", "Hominoidea", "Hominidae", "Homininae", 
           "Homo sapiens")

age <- 1:length(clade)  # Assign numeric values based on the order

# Create a DataFrame with the clade and their corresponding age
phylogeny_df <- data.frame(clade = clade, age = age)
phylogeny_df$clade <- factor(phylogeny_df$clade, levels=clade)
```

```{r}
# merge with TE data
hm_TE <- HmPtC1$DEobject$te_res %>%
    data.frame() %>%
    mutate(gene = rownames(.)) %>%
    inner_join(df_te_extract, join_by(gene==TE))

hm_TE$species <- factor(hm_TE$species, levels=clade)

g_hm_te <- ggplot(hm_TE, aes(x=species, y=baseMean)) +
    geom_boxplot(fill = "#76D7C4", color="black", outlier.shape = NA) +
    xlab("") +
    ylab("exp") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 60, vjust= 0.6, hjust=0.5))

g_hm_te_2 <- ggplot(hm_TE, aes(x=species, y=baseMean)) +
    geom_boxplot(fill = "#76D7C4", color="black", outlier.shape = NA) +
    xlab("") +
    ylab("exp") +
    ylim(0, 1000) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 60, vjust= 0.6, hjust=0.5))
```

merge two graphs

```{r}
g_hm_kznf_te <- ggarrange(g_hm_kznf, g_hm_te, ncol = 1)
ggsave("../figures/continuous_age_check_hmc1.jpg", dpi=400, width=6, height = 10)
```

We would like to put the number of TEs and KRAB-ZNFs in a phylogeny tree

```{r}
#337 KRAB-ZNFs
kznf_phylo <- kznf_infer %>%
    left_join(gentree[,c(1,3)], join_by(ensembl_gene_id==gene)) 
write.csv(kznf_phylo, file="../tables/kznf_phylo_age.csv", row.names=F)
#kznf_phylo <- read.csv("../tables/kznf_phylo_age.csv")

#1151 TEs
hg38_TE <- read.csv("~/github/pBrain/data/hg38rmsk_info.csv")
TE_phylo <- hg38_TE %>% 
    left_join(df_te_extract, join_by(repName==TE)) %>%
    mutate(age = ifelse(repName %in% te_infer$NM, "young", "old"))
write.csv(TE_phylo, file="../tables/TE_phylo_age.csv", row.names=F)
#TE_phylo <- read.csv("../tables/TE_phylo_age.csv")
```

Then we need to calculate the exact number

```{r}
TE_phylo_preprocess <- TE_phylo[,c(1,5,6)] %>%
    full_join(te_infer[,c(2,3)], join_by(repName==NM)) %>%
    mutate(clade = ifelse(is.na(clade), OS, clade)) %>%
    group_by(clade, age) %>%
    summarise(count=n())
    
```
